### ISSUE TITLE
not working for request sent with json body

### ISSUE THREAD

**Issue by shaoxp** [toboid/express-correlation-id#37]
i found one issue when integrating this lib. please see whether you can reproduce it or not.

when sent request with json request, the correlate id will always be undefined. please send following test request.

Thanks.

`GET / HTTP/1.1
Host: localhost
Content-Type: application/json
User-Agent: PostmanRuntime/7.16.3
Accept: */*
Cache-Control: no-cache
Host: localhost
Accept-Encoding: gzip, deflate
Content-Length: 2
Connection: keep-alive
cache-control: no-cache

{}`

**Comment by shaoxp** [comment]
if i comment out following code. the correlate work correctly.

`app.use(express.json());`

**Comment by OlexiyZh** [comment]
I also faced with this issue. Correlation id is generated and working well if you use `bodyParser` or `express.json()` as middleware before `correlator`.

**Comment by toboid** [comment]
Thanks both, I've added a note to the readme to
