### ISSUE TITLE
express-correlation-id do not work with multipart (upload file)

### ISSUE THREAD

**Issue by ddkhanh** [toboid/express-correlation-id#44]
I have an api to support upload file from client side,  router used to handle request failed to obtain the correlation-id  from req object using req.correlationId()
 
![image](https://user-images.githubusercontent.com/5151868/85407120-fe04d580-b58c-11ea-9e52-7ad9992b3ad3.png)

I did a deeper debug and saw that processMultipart will proceed the upload within a busybox that cause req.correlationId() return undefined value
Do we need any specification to get over this issue?

![image](https://user-images.githubusercontent.com/5151868/85407174-12e16900-b58d-11ea-9268-9e2bb4e2062c.png)

**Comment by ddkhanh** [comment]
Just figure out the issue is that I placed midddle express-fileupload below express-correlation-id that will cause correlation-id lost.

Re-order the list then it worked!
app.use(fileUpload())
app.use(correlator());

**Comment by ddkhanh** [comment]
@toboid: Please update README for this issue.

**Comment by toboid** [comment]
Hi @ddkhanh, there is a note regarding this in the `Middleware usage` section. If you think it could be made clearer I'd welcome a PR for that

**Comment by ddkhanh** [comment]
Hi @toboid ,
Thanks for your hint, but the current note in Middleware usage section is quite ambiguous as we don't know where we should place the express-correlation-id below which.

And, there is an open PR to clarify Middleware usage
https://github.com/toboid/express-correlation-id/issues/38
Could you help to check and update the note?
Thanks
