### ISSUE TITLE
`TypeError: AsyncLocalStorage is not a constructor` (node v12)

### ISSUE THREAD

**Issue by OhadR** [toboid/express-correlation-id#55]
on node v12.16.1, i get `TypeError: AsyncLocalStorage is not a constructor`

is it a known issue?

```
TypeError: AsyncLocalStorage is not a constructor
    at Object.<anonymous> (C:\Ohads\Dev\projects\smart-adas\smart-adas\node_modules\correlation-id\index.js:6:27)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)

Process finished with exit code 1

```

**Comment by toboid** [comment]
Hi there, you'll need to use node >=12.17.0 to work with the latest version of this package. This is noted in the engines section of the package.json but i'll add that to the readme to make it clearer.

If you're unable to use node  >=12.17.0 you can try version 1.3.1 this package instead.

**Comment by OhadR** [comment]
Thanks a lot. Version 1.3 does work for me.
Thanks!

**Comment by szulcus** [comment]
I have the same problem with. I've probably tried every possible version of the package and node, and the problem is still exist. I give up :/

**Comment by toboid** [comment]
Hey, I'd recommend deleting your node_modules & package lock file then re-installing the appropriate version for depending on your node version as per the advice above. 

However keep in mind that the node 12 is long since out of support and no longer receiving patches - https://nodejs.org/en/about/previous-releases.
