### ISSUE TITLE
There isn't way to set the correlation id.

### ISSUE THREAD

**Issue by medoussboug** [toboid/express-correlation-id#69]
It will be interesting to have a way to set the correlation id, that way the use of this library will be expanded to support asynchronous communication, since from service A we can send an event to Service B and for now there is isn't a way (to my knowledge) to propagate the correlation id of service A to service B.

**Comment by toboid** [comment]
Hi @medoussboug, it's currently possible to set the correlation id based on an inbound request header.

e.g. let's say we have two services `A` and `B` and `A` is making a call to `B`.
If `A` provides a header of `x-correlation-id` then the correlation mw in service `B` will automatically pick that value up from the request headers and use it to set the correlation id for that request.

`x-correlation-id` is the default name for that header but it's configurable (when initialising the middleware).

Would this solve your scenario?
If not i'd be happy to consider extending if you have provide any more detail about your situation.

**Comment by medoussboug** [comment]
Hello, thanks for the reply, I understand that part, but I think I poorly explained my use case. 

e.g. Basically for example we have service `A` that manages users and service `B` that sends notification... Now let's look at the following use case, service `A` receives an HTTP request to register a user (it generates the correlation ID), it persists the user in the database and sends a Kafka event to service `B`. In this case how can `A` propagate the correlation ID generated to the service `B` so that it can be used in the service `B` with `getId()`.

Note that when sending events with kafka for example, there can't be a header `x-correlation-id`. Is this already implemented or should it be a feature request?

**Comment by toboid** [comment]
Hey @medoussboug thanks or this information.
I've published a new version 3.0.1 that will support this by providing `correlator.setId` and `req.setCorrelationid` functions.

For example you could create a new middleware to set the id:

```js
app.use(correlator());
app.use((req, res, next) => {
  req.setCorrelationId('my-new-id');
  next();
});
```

Hope this helps

**Comment by toboid** [comment]
Will close but please do let me know how you get on with that

**Comment by toboid** [comment]
Interested to hear how you get on.  Will leave open for a bit

**Comment by medoussboug** [comment]
Thanks man for the quick fix I will give it a try and see how it goes, you are the best.

**Comment by medoussboug** [comment]
The adjustment you added enables setting the correlation Id of incoming HTTP requests, but the use case I am referring to is to have a mechanism who accepts setting the correlation Id from the incoming requests using the header (which is already implemented), the other one is to from given Events, here is a link to the code, I made a small repo trying to replicate what I have in mind: https://github.com/medoussboug/notification-service-ts/blob/3e31f523e3648873d8d139907166aa07c40e096d/src/clients/consumers/eventConsumer.ts#L28

For example in the code that I shared that service has no endpoints, but is only used as an event consumer, there for I need a way to propagate the correlation id that comes from the events, in order to use it for logging. As you can see in this code I used a workaround using the AsyncLocalStorage.

I think that the `express-correlation-id` library can benefit of something similar, I am not sure of how to be honest since I don't have enough context about the implementation of this library.

**Comment by toboid** [comment]
I see, that makes sense now. Take a look at https://github.com/toboid/correlation-id. `express-correlation-id` is just a wrapper around that to be make it easy to use it in the context of express http requests. In your case you don't that so using `correlation-id` directly will do the trick.

**Comment by medoussboug** [comment]
Thanks man, sorry for any troubles.

**Comment by toboid** [comment]
No probs 😄
